/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RrethNeshRouteImport } from './routes/rreth-nesh'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SherbimetIndexRouteImport } from './routes/sherbimet.index'

const RrethNeshRoute = RrethNeshRouteImport.update({
  id: '/rreth-nesh',
  path: '/rreth-nesh',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SherbimetIndexRoute = SherbimetIndexRouteImport.update({
  id: '/sherbimet/',
  path: '/sherbimet/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/rreth-nesh': typeof RrethNeshRoute
  '/sherbimet/': typeof SherbimetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/rreth-nesh': typeof RrethNeshRoute
  '/sherbimet': typeof SherbimetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/rreth-nesh': typeof RrethNeshRoute
  '/sherbimet/': typeof SherbimetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/galeria' | '/kontakt' | '/rreth-nesh' | '/sherbimet/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/galeria' | '/kontakt' | '/rreth-nesh' | '/sherbimet'
  id: '__root__' | '/' | '/galeria' | '/kontakt' | '/rreth-nesh' | '/sherbimet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriaRoute: typeof GaleriaRoute
  KontaktRoute: typeof KontaktRoute
  RrethNeshRoute: typeof RrethNeshRoute
  SherbimetIndexRoute: typeof SherbimetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rreth-nesh': {
      id: '/rreth-nesh'
      path: '/rreth-nesh'
      fullPath: '/rreth-nesh'
      preLoaderRoute: typeof RrethNeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sherbimet/': {
      id: '/sherbimet/'
      path: '/sherbimet'
      fullPath: '/sherbimet/'
      preLoaderRoute: typeof SherbimetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriaRoute: GaleriaRoute,
  KontaktRoute: KontaktRoute,
  RrethNeshRoute: RrethNeshRoute,
  SherbimetIndexRoute: SherbimetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
